### ISSUE TITLE
"solo link" provided in a room provides "group scene" when using own socket server

### ISSUE THREAD

**Issue by Jumper78** [steveseguin/vdo.ninja#880]
I am testing vdo.ninja with an own socket server (see https://github.com/steveseguin/websocket_server). When I create a room with one performing director and one guest, I do get a solo link for the director that looks normal. When I copy the solo link of the guest, it already has  `&pie` as an option at the end of the link (in my opinion, that should not be there). When using those two links, they give the same result as the link for the group scene: I always see both of the streams at the same time, the director stream next to the guest stream, instead of just the stream of the director or just the stream of the performer.
I have seen this behaviour in 18.1 and 18.2. When I uncomment `session.wss` and `session.pie` in the `index.html` and go back to the normal socket server, the problem disappears. Since 18.1 was the first version that allowed having your own socket server, the problem has probably nothing to do with the update to version 18 but is related to `session.wss` and/or `session.pie` parameters in the config.
The links provided by the director interface seem to be normal: they all have individual `STREAMID`s behind the `?view=`. The only exception is the mentioned `&pie` behind the link of the guest. So, it looks to me that the problem lies in the handling when watching a stream and not in the user interface of the director.

**Comment by Jumper78** [comment]
Please let me know if you have suggestions what I could test or if you have hints where I could look in the source code.

**Comment by steveseguin** [comment]
I just tested and confirmed there is an issue. I'll fix it and update github and vdo.ninja/beta once done.  Thank you for pointing out the issue.

**Comment by steveseguin** [comment]
I patched it.  I have the code up on beta for testing (using &pie=someapikey) or you can download the current development version from the 18.3 beta branch, linked below:

https://vdo.ninja/beta/
https://github.com/steveseguin/vdo.ninja/tree/v18.3beta

**Comment by Jumper78** [comment]
Thank you very much for the very, very fast response!
I had a quick check and it look much better. The solo link for the director is now working. The solo link for the guest still has some hick-ups, though.
The solo link for the guest has still `&pie` attached to it. Since I did set up my own socket server and I am not using piesocket.com, this seems to be wrong. When I copy and paste the guest solo link into a browser, no video stream is established unless I remove the `&pie`. Removing it establishes the video stream, that is the good news.
The bad news: as soon as I copy the link of the guest into the browser, the video stream in the control center of the room disappears. The control of the guest stream (transfer, message, hangup, solo talk, ...) is still visible, but the video stream disappears. This does not happen if I remove the `&pie` from the link of the solo stream. --> So, that also does not sound too bad!

**Comment by steveseguin** [comment]
Thank you for the details of the issue. I'll investigate further and try to replicate.  

Just off the top of my head, I think I had it so if you set `session.pie=true;` in your own self-deployment, you don't need to add &pie.  &pie should only be needed I think if you are passing an API Key to the parameter,  in the case you don't intend to self-deploy the code. If you are self-deploying, just setting `session.pie=true;` should be enough.  

Probably a bug though, based on what you said.  we'll see. sorry for the issue

**Comment by Jumper78** [comment]
You are right, I have set `session.pie=true`. That might be the reason for the wrong behaviour. I thought that was needed for using my own socket server ... but that was probably a mistake.
I will check tonight ...

**Comment by steveseguin** [comment]
session.pie works for both non-pie and pie-hosted websocket servers. I should rename the value to something else, as it confusing.  The logic used to decide if the &pie value is added to an invite URL is as follows:
```
if (session.pie){
   if (session.pie!==true){
      pie = "&pie="+session.pie;
    }
}
```
In essence, if pie is not "true", but rather an API key, it will add the API key to the URL.  If session.pie is exactly true, then it won't add the API key to the URL, as it assumes the API key is already added to the session.wss value, as seen below:

![image](https://user-images.githubusercontent.com/2575698/123049600-b8f8c680-d3cd-11eb-89bf-28003da7f0cd.png)

I'll rename the session.pie to something else; this hopefully will help clarify the issue for others in the future.  If the issue persists though, let me know.  not many people, if any, have so far made use of this feature really.

**Comment by steveseguin** [comment]
Found a small bug where &pie was added to one of the invite links.  I fixed it. I also changed the `session.pie` variable to `session.customWSS`, which hopefully helps avoid confusion also in the future
https://github.com/steveseguin/vdo.ninja/tree/v18.3beta
https://vdo.ninja/beta
Thank you

**Comment by Jumper78** [comment]
You must have missed a `session.pie` somewhere in your code! ;-)
I downloaded the latest v18.3beta and changed from `session.pie = true;` to `session.customWSS = true;` and that broke the complete functionality of my self-hosted vdo-ninja. To make the custom-WSS work again, I had to add `session.customWSS = true;` as well as `session.pie = true;` to the configuration in the `index.html`. Only when I have both lines in the code at the same time, the custom WSS works.
I am still evaluating if your other fixes solved the original problem.

**Comment by Jumper78** [comment]
I also still have the problem that `&pie` is added to the url of my guest. This is strange. I can follow your logic and you are right, that should not happen according to the code you quoted above.
Maybe both of the problems are related to me still having some old file version in a cache (webserver, browser, ...)? I will keep testing.

**Comment by steveseguin** [comment]
can you double check you have cleared the browser cache?  

CTRL + refresh on PC chrome.

I'll have time to re-test it all though in a moment.  Please make sure you are testing with the v18.3 beta branch and not master

**Comment by Jumper78** [comment]
Keep your horses! The `&pie` problem is solved. I did not clear my cache properly. I will now also check the `session.customWSS` vs. `session.pie` as well.

**Comment by Jumper78** [comment]
I have double checked with browser caches cleared on both sides and that solved both problems.
Thank you very much for your help!

**Comment by Jumper78** [comment]
Problem has been fixed in one of the 18.3beta commits on Jun 23, 2021. It is fixed with 1a00eaf2b70f22592aea72f14500bb390be02abf.
